
  ventory-android:
    name: Ventory Android Build
    max_build_duration: 120
    environment:
      unity: 2022.3.22f1
      vars:
        UNITY_EMAIL: $UNITY_EMAIL
        UNITY_PASSWORD: $UNITY_PASSWORD
    scripts:
      - name: Instalar modulos Android
        script: |
          yes n | /Applications/Unity\ Hub.app/Contents/MacOS/Unity\ Hub \
            -- --headless install-modules \
            --version 2022.3.22f1 \
            -m android android-sdk-ndk-tools \
            -a arm64 || true

      - name: Ativar Unity Personal
        script: |
          /Applications/Unity/Hub/Editor/2022.3.22f1/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -logFile /dev/stdout \
            -username "$UNITY_EMAIL" \
            -password "$UNITY_PASSWORD" \
            -quit || true

      - name: Build APK Android
        script: |
          /Applications/Unity/Hub/Editor/2022.3.22f1/Unity.app/Contents/MacOS/Unity \
            -batchmode -quit \
            -logFile /dev/stdout \
            -projectPath . \
            -buildTarget Android \
            -executeMethod BuildScript.BuildAndroid \
            -nographics

    artifacts:
      - "*.apk"
